### ISSUE TITLE
expose `text` property in place of image icon and/or svg icon compatibility?

### ISSUE THREAD

**Issue by jaysaurus** [nstudio/nativescript-floatingactionbutton#100]
Hiya,

Kind of 2 issues (but related close-enough to warrant reporting as one issue as I suspect either/or would be satisfactory for most people).

Vue Nativescript supports font-awesome OOB via a .ttf file, and it really isn't much work to switch to material.io etc. It'd be fantastic therefore if - rather than having to download anything else - i could do something like the following:

```vue
<fab @tap="foo"
        row="1"
        text.decode="f067"
        rippleColor="#f1f1f1"
        class="fab-button" />
```
thereby allowing the user to size the font using `font-size` as the css.

**alternatively**
I tried to use an svg I'd downloaded as my icon on the FAB and it didn't work. I'm not a huge fan of using png et al unless I have to in the structural design of applications.  Please would it be possible to support svg or equivalent vector graphics as part of the FAB icon's options?

**Comment by bradmartin** [comment]
On Android, I believe the FloatingActionButton natively extends the Image widget which is why it's currently only exposed for images and not SVG or fonts.

It is possible to do something like this, but would require a bit of work to implement the feature. Not saying it's impossible but I personally do not have the time to implement this feature. I'll leave this open if someone wants to work on it though as a future enhancement.

**Comment by xuhcc** [comment]
I recently posted a workaround for text icon here https://github.com/nstudio/nativescript-floatingactionbutton/issues/53#issuecomment-519836501 
It should be trivial to intergrate it into this plugin, however I don't know how to do a similar thing on iOS.
